export type Project = {
  slug: string;
  name: string;
  sector: string;
  scope: string;
  objective: string;
  palette: string;
  signal: string;
  visual: string;
  status: string;
  route: string;
  caseTitle: string;
  caseSummary: string;
  audience: string;
  architecture: string[];
  decision: string;
  tradeoff: string;
  interaction: string;
  responsive: string;
  system: string;
};

export const projects: Project[] = [
  {
    slug: "orynt-ai", name: "ORYNT AI", sector: "Product & analytics", scope: "Product design · responsive UI · web development", objective: "Turn scattered project updates into a clear, inspectable view of work.", palette: "#183D35", signal: "#A7BEA4", visual: "/images/orynt-marketing-desktop.webp", status: "Independent Concept Project", route: "https://vaeltx-orynt-ai-concept.vercel.app/", caseTitle: "A clearer picture of the work.", caseSummary: "An editorial product website and a working operations workspace connect project discovery, explainable signals and exportable reports using a fixed synthetic dataset.", audience: "An operations lead who needs to understand project health, examine a signal and take the underlying data into a report.", architecture: ["Understand the product", "Explore the workspace", "Find a project", "Inspect a signal", "Build a report"], decision: "Make every useful number traceable to the same synthetic snapshot.", tradeoff: "The concept prioritizes an inspectable experience over live integrations, authentication or commercial AI.", interaction: "Search, filters and reporting controls recalculate the visible synthetic observations.", responsive: "Desktop navigation becomes a mobile drawer; dashboards stack and data tables retain their own scroll area.", system: "Evergreen fields, warm paper, editorial typography and quiet, purposeful data visualization."
  },
  {
    slug: "aster-form", name: "ASTER & FORM", sector: "Editorial & booking", scope: "Visual identity · web design · reservation UX", objective: "Bring a premium studio identity into a clear, considered service and reservation journey.", palette: "#302A24", signal: "#BEAE92", visual: "/images/aster-marketing-desktop.webp", status: "Independent Concept Project · Full-stack certification pending", route: "https://asterandform.vercel.app/preview", caseTitle: "A considered experience, from first impression to next step.", caseSummary: "A fictional interior consultation atelier pairs premium editorial design with a safe interactive reservation walkthrough and synthetic client and studio views. Full-stack certification remains pending.", audience: "A visitor exploring a fictional interior studio, comparing consultations and understanding the next step.", architecture: ["Discover the visual identity","Compare the consultations","Explore the safe reservation walkthrough","Inspect synthetic client and studio views"], decision: "Keep the public walkthrough separate from protected reservations.", tradeoff: "The synthetic preview demonstrates interface behavior without certifying production authentication or private workflows.", interaction: "Choose a fictional service and sample time, then inspect a clearly simulated confirmation.", responsive: "Editorial imagery, service information and reservation controls adapt to narrow screens.", system: "Warm neutral fields, expressive serif typography, atmospheric concept imagery and restrained service navigation."
  },
  {
    slug: "northstar-roofing", name: "Northstar Roofing", sector: "Local service", scope: "Strategy · UX · UI · implementation intent", objective: "Help a homeowner understand the next safe step before requesting an inspection.", palette: "#102236", signal: "#E85A24", visual: "/images/northstar-residence.webp", status: "Independent Concept Project", route: "/concepts/northstar-roofing", caseTitle: "Trust before the first conversation.", caseSummary: "A local-service system that connects service fit, area discovery, inspection context and a short quote path without inventing reviews or credentials.", audience: "A homeowner who may have noticed a leak, storm damage or an aging roof and needs to know whether an inspection is the right next step.", architecture: ["Orient around what the homeowner sees", "Choose a service path", "Check a clearly illustrative service area", "Understand what an inspection shows", "Request a conversation"], decision: "Separate urgent concerns from planned work before presenting the service taxonomy.", tradeoff: "A guided first choice adds a small step; it reduces the work of translating roofing jargon into a request.", interaction: "A problem selector updates the next-step explanation; the quote form preserves context and clearly states that no booking is made.", responsive: "On narrow screens, contact choices precede decorative media; the service selector becomes a stacked radio group and the persistent action hides around forms and footer content.", system: "Navy utility rails, warm paper, clear structural headings, inspection annotations and direct orange actions."
  },
  {
    slug: "mira-atelier", name: "Mira Atelier", sector: "Independent artist", scope: "Art direction · UX · gallery · commission journey", objective: "Let visitors explore existing work or begin a commission without mixing the two decisions.", palette: "#F5F0E8", signal: "#7D2F3B", visual: "/images/mira-moon-garden.svg", status: "Independent Concept Project", route: "/concepts/mira-atelier", caseTitle: "A gallery that keeps discovery and commissions distinct.", caseSummary: "An editorial gallery and a more practical commission path share one artist identity while keeping discovery, product details and custom work distinct.", audience: "A visitor who wants to appreciate an original illustration, ask about a piece or explore a custom commission.", architecture: ["Enter through a single artwork", "Choose Work, Commissions or Shop", "Inspect a piece or understand the commission process", "Send a contextual request"], decision: "Give commissions and existing work separate visual rhythms instead of forcing both into a single product grid.", tradeoff: "The routes are more distinct than a conventional top-level shop; each visitor sees clearer language for their intent.", interaction: "Artwork tiles open a keyboard-accessible viewer; the commission path uses a short local-only form demonstration.", responsive: "Artwork gets edge-to-edge crops while titles and purchase/commission facts retain safe text margins; gallery rhythm changes to a single column.", system: "Warm paper, literary serif display, generous negative space, original digital concept artwork and quiet wine accents."
  },
  {
    slug: "axiom-strategy", name: "Axiom Strategy", sector: "B2B consulting", scope: "Information architecture · frameworks · editorial UX", objective: "Make a complex advisory offer legible through questions, decision models and explicit scenario limits.", palette: "#F6F5F0", signal: "#163B31", visual: "/images/axiom-framework.svg", status: "Independent Concept Project", route: "/concepts/axiom-strategy", caseTitle: "A clear structure for complex decisions.", caseSummary: "A dense B2B system organizes services, industries, illustrative scenarios and long-form insights around decisions rather than generic capability cards.", audience: "A decision-maker facing an ambiguous growth, market or operating question and looking for a structured way to examine it.", architecture: ["Name the decision pressure", "Choose a capability or industry lens", "Inspect an illustrative scenario", "Read the decision model", "Start a high-context conversation"], decision: "Use service and industry indexes as editorial rows, then reveal a six-stage decision framework only when requested.", tradeoff: "The framework adds purposeful reading time; it avoids implying that complex consulting outcomes fit a one-click flow.", interaction: "Framework stages disclose their questions and outputs in reading order; diagrams never animate fictional performance data.", responsive: "Sticky chapter rails become inline disclosure controls and comparison tables become labeled stacks.", system: "Editorial serif for selected theses, mono labels, deep evergreen, restrained diagrams and information-rich white space."
  },
  {
    slug: "vault-tcg", name: "Vault TCG", sector: "Collectibles commerce", scope: "Discovery · search · filtering · cart demo", objective: "Let a collector compare fictional cards by set, condition and availability before a clearly demo-only checkout.", palette: "#0B0C10", signal: "#C9A85E", visual: "/images/vault-card.svg", status: "Independent Concept Project", route: "/concepts/vault-tcg", caseTitle: "Collector detail, made clear.", caseSummary: "A dark commerce system demonstrates discovery, search, condition selection, inventory states, cart behavior and a checkout flow that never processes payment.", audience: "A collector who knows a set, card or condition and wants specific details before adding an item to a cart.", architecture: ["Search or browse a fictional set", "Filter by condition and availability", "Inspect card details", "Add to a local demo cart", "Review an explicitly non-payment checkout"], decision: "Keep price, condition, set and stock state visible before hover; only use a gold foil response on one original concept asset.", tradeoff: "The catalog uses fictional original artwork instead of familiar licensed TCG imagery, so its UX can be evaluated without implying real inventory.", interaction: "Filters update query state locally, condition changes update the product display, and cart contents persist only in this browser.", responsive: "Filters move into a keyboard-controlled sheet, product facts stay above accordions and the cart becomes a full-screen review.", system: "Obsidian panels, fine rules, collector-grade metadata, original fantasy card art and precise commerce feedback."
  },
];

export const parentRoutes = ["work", "work/orynt-ai", "work/aster-form", "work/northstar-roofing", "work/mira-atelier", "work/axiom-strategy", "work/vault-tcg", "services", "process", "standards", "about", "contact", "privacy"];
export const projectBySlug = Object.fromEntries(projects.map(project => [project.slug, project])) as Record<string, Project>;

export const services = [
  { title: "Web design", text: "Information architecture, page hierarchy, visual direction and responsive states for a site people can understand.", output: "Page map · key views · design system" },
  { title: "Web development", text: "Implementation that carries layout, accessibility and interaction decisions through to the browser.", output: "Components · states · responsive behavior" },
  { title: "Focused redesign", text: "A clear look at what should change, what can stay and where migration risk needs attention.", output: "Friction review · priorities · rebuild plan" },
  { title: "Landing pages", text: "A disciplined message path from the visitor’s question to a useful next action.", output: "Message hierarchy · proof · action path" },
  { title: "UX/UI systems", text: "Flows, reusable patterns and component states that keep related screens coherent.", output: "Flows · patterns · interaction rules" },
  { title: "Implementation support", text: "Scoped production help for an agency or internal team, with an explicit handoff boundary.", output: "Page delivery · QA · documentation" },
];

export const processSteps = [
  { name: "Frame", question: "What must the site make obvious?", output: "Brief · priorities · risks · success definition" },
  { name: "Structure", question: "What should people see, and in what order?", output: "Sitemap · page goals · content hierarchy · wireframes" },
  { name: "Design", question: "What should the experience feel like while staying usable?", output: "Art direction · visual system · responsive views" },
  { name: "Build", question: "Does the implementation preserve the design intent?", output: "Components · interactions · content · performance constraints" },
  { name: "Verify", question: "Does the finished experience work under real conditions?", output: "Responsive · keyboard · content · performance · launch QA" },
];

export type ConceptRoute = { path: string; label: string; kind: string; title: string; description: string; sections: { heading: string; body: string; items?: string[] }[]; cta?: { label: string; href: string } };

function route(path: string, label: string, kind: string, title: string, description: string, sections: ConceptRoute["sections"], cta?: ConceptRoute["cta"]): ConceptRoute {
  return { path, label, kind, title, description, sections, cta };
}

const northstar: ConceptRoute[] = [
  route("", "Home", "home", "Know what your roof needs before you commit to the next step.", "A clear inspection path for repair concerns, storm damage and planned replacement. This is an independent concept by VAELTX; no roofing service is offered.", [{ heading: "Start with what you can see", body: "A leak, a storm or an aging roof lead to different questions. Choose the situation that sounds closest; you do not need to diagnose the roof." }, { heading: "Service fit", body: "Repair, replacement, storm damage and inspections are separate paths with plain-language next steps." }, { heading: "An inspection should leave a record", body: "The report specimen shows how an observation, its context and a next question can sit together. It is illustrative, not a real assessment." }], { label: "Explore services", href: "/concepts/northstar-roofing/services" }),
  route("services", "Services", "index", "The right service starts with the right question.", "A service index designed around homeowner situations rather than construction jargon.", [{ heading: "Roof repair", body: "A suspected leak, flashing concern or localized failure should be documented before a repair scope is defined.", items: ["What is visible", "What needs inspection", "What a written scope should explain"] }, { heading: "Roof replacement", body: "Material, roof condition and repair history shape a replacement conversation. The concept avoids promising a product or timeline." }, { heading: "Storm damage", body: "Keep away from unsafe areas. A calm inspection path can collect context without using panic language." }, { heading: "Roof inspection", body: "A useful inspection explains observations and the questions that remain; it does not force an immediate purchase." }], { label: "Request an inspection", href: "/concepts/northstar-roofing/request-an-inspection" }),
  route("services/roof-repair", "Roof repair", "service", "Start with the source, not a guess.", "An illustrative service page for leaks, damaged flashing and localized roof concerns.", [{ heading: "What this path is for", body: "A visitor can describe what they have noticed without deciding which component failed." }, { heading: "What an inspection can clarify", body: "The demonstration separates visible symptoms from findings that require an on-site professional assessment." }, { heading: "Before work is discussed", body: "A written scope should identify the observed issue, proposed work and any remaining uncertainty. No repair is booked from this concept." }], { label: "Request a roof inspection", href: "/concepts/northstar-roofing/request-an-inspection" }),
  route("services/roof-replacement", "Roof replacement", "service", "Compare options before replacing.", "A decision page for planned replacement, without invented materials, pricing or warranty terms.", [{ heading: "What shapes the decision", body: "Current condition, repair history, roof geometry and material choice need to be considered together." }, { heading: "Options should be explained", body: "A clear proposal describes the selected material, what is included and what changes the scope." }, { heading: "Written terms matter", body: "Warranty duration and certification stay unclaimed until a real business confirms them." }], { label: "Discuss a replacement", href: "/concepts/northstar-roofing/contact" }),
  route("services/storm-damage", "Storm damage", "service", "A calm next step after a storm.", "An urgent-intent page that prioritizes safety and clear documentation over dramatic claims.", [{ heading: "Stay clear of damaged areas", body: "Do not climb onto a roof or enter a space that may be unsafe. The concept offers no emergency service." }, { heading: "Record what you can safely see", body: "A date, an exterior observation and any immediate water entry can help frame a later professional conversation." }, { heading: "Inspection before scope", body: "The path explains how observations may be documented without promising insurance approval or a particular repair." }], { label: "See the inspection path", href: "/concepts/northstar-roofing/services/roof-inspection" }),
  route("services/roof-inspection", "Roof inspection", "service", "An inspection should answer useful questions.", "A sample structure for explaining what is looked at and how observations might be recorded.", [{ heading: "What is checked", body: "Roofing material, flashing junctions and drainage paths are shown as illustrative inspection categories; the real scope belongs to a qualified provider." }, { heading: "What the homeowner receives", body: "An inspection record can pair a photo with an observation, condition note and next question." }, { heading: "No diagnosis by form", body: "The quote path collects context only. It does not diagnose a roof or create a booking." }], { label: "Request an inspection", href: "/concepts/northstar-roofing/request-an-inspection" }),
  route("service-areas", "Service areas", "areas", "A service area should be easy to verify.", "This map and the districts below are fictional UI examples. They do not describe real coverage.", [{ heading: "Illustrative districts", body: "North, Central and Lakeside show a searchable area pattern without publishing a false address or city claim." }, { heading: "Useful city pages", body: "A real location page needs unique service availability and useful local details; duplicated doorway pages are not a substitute." }], { label: "Explore the city-page pattern", href: "/concepts/northstar-roofing/service-areas/sample-city" }),
  route("service-areas/north-district", "North district", "city", "North district · illustrative service-area pattern.", "A fictional locality used to demonstrate a service-area route. This is not a real coverage claim.", [{ heading: "What belongs on a real city page", body: "Verified availability, local process details and the relevant next action. No location data is invented for this concept." }], { label: "Back to service areas", href: "/concepts/northstar-roofing/service-areas" }),
  route("service-areas/central-district", "Central district", "city", "Central district · illustrative service-area pattern.", "A fictional locality used to demonstrate a service-area route. This is not a real coverage claim.", [{ heading: "What belongs on a real city page", body: "Verified availability, local process details and the relevant next action. No location data is invented for this concept." }], { label: "Back to service areas", href: "/concepts/northstar-roofing/service-areas" }),
  route("service-areas/lakeside-district", "Lakeside district", "city", "Lakeside district · illustrative service-area pattern.", "A fictional locality used to demonstrate a service-area route. This is not a real coverage claim.", [{ heading: "What belongs on a real city page", body: "Verified availability, local process details and the relevant next action. No location data is invented for this concept." }], { label: "Back to service areas", href: "/concepts/northstar-roofing/service-areas" }),
  route("service-areas/sample-city", "Sample city page", "city", "Roofing service in a sample city.", "Illustrative city-page pattern only. This is not a real location, provider or service availability statement.", [{ heading: "Local page structure", body: "A useful city page starts by confirming coverage, then explains the services and next step relevant to that place." }, { heading: "Facts that must be verified", body: "Service radius, weather context, licenses, coverage and any local reference need a real source before publication." }], { label: "Review the service-area pattern", href: "/concepts/northstar-roofing/service-areas" }),
  route("about", "About", "about", "A clear process is part of a roof decision.", "A concept company profile showing how to describe an operating approach without inventing a team or credentials.", [{ heading: "Explain the work", body: "A real provider would state who performs inspections, how findings are shared and how a work scope is approved." }, { heading: "Credentials belong to evidence", body: "License, insurance, manufacturer certifications, staff and history are intentionally omitted here." }], { label: "See the inspection process", href: "/concepts/northstar-roofing/services/roof-inspection" }),
  route("reviews", "Reviews", "reviews", "Verified feedback belongs to its source.", "This layout demonstrates an honest review page without invented testimonials or rating totals.", [{ heading: "No reviews are fabricated", body: "Customer feedback would appear only after a real source is connected and the wording is verified." }, { heading: "Review integration state", body: "The empty state is intentional: a clear note is more trustworthy than placeholder stars." }], { label: "Request an inspection", href: "/concepts/northstar-roofing/request-an-inspection" }),
  route("warranty", "Warranty", "warranty", "Warranty details should be written down.", "A simple structure for explaining coverage without making up duration, exclusions or manufacturer terms.", [{ heading: "What a real warranty page needs", body: "Coverage term, exclusions, responsible party and claim path must be confirmed before publishing." }, { heading: "What this concept can say", body: "Ask for the applicable terms in writing before work begins. No duration or guarantee is implied." }], { label: "Ask about coverage", href: "/concepts/northstar-roofing/contact" }),
  route("request-an-inspection", "Request an inspection", "quote", "Describe what you are noticing.", "The form below is a local demonstration. No real business receives or stores these entries.", [{ heading: "A short context is enough", body: "Name, email, timing and a plain-language observation demonstrate a clear request flow." }], { label: "Contact VAELTX", href: "/contact" }),
  route("request-a-quote", "Request a quote", "quote", "Start with context, not a diagnosis.", "This demo shows validation and a confirmation state; it cannot book an inspection or provide a roof quote.", [{ heading: "No appointment is created", body: "The ZIP and need fields are kept within the page and discarded when you leave." }], { label: "Contact VAELTX", href: "/contact" }),
  route("contact", "Contact", "contact", "Questions about the concept?", "This fictional roofing business has no phone, address or booking service. Contact VAELTX about the design concept instead.", [{ heading: "Concept boundary", body: "No real Northstar Roofing business is represented. Do not use this page to request roofing work." }], { label: "Contact VAELTX", href: "/contact" }),
  route("faq", "FAQ", "faq", "Questions before an inspection.", "A concept FAQ uses clear, non-diagnostic answers and leaves unknown business facts unclaimed.", [{ heading: "Are these real roofing services?", body: "No. Northstar Roofing is an independent concept project by VAELTX." }, { heading: "Does this page book an appointment?", body: "No. The form is a local interaction demonstration and sends nothing." }, { heading: "Are the service areas real?", body: "No. The districts and sample city are fictional layout examples." }, { heading: "Are warranty terms included?", body: "No duration or coverage is stated because no real provider terms exist." }, { heading: "Are there customer reviews?", body: "No. The review pattern explicitly reserves space for verified feedback." }], { label: "View the inspection form", href: "/concepts/northstar-roofing/request-an-inspection" }),
];

const mira: ConceptRoute[] = [
  route("", "Home", "home", "Illustration for stories, spaces and people worth remembering.", "Original concept artwork, existing pieces and a separate path for commissioning something personal.", [{ heading: "Two ways into the work", body: "Explore completed pieces in the gallery, or follow the commission route to understand how a new idea becomes an artwork." }, { heading: "A slower look", body: "Artwork opens in a focused viewer with materials, title and context kept close to the image." }, { heading: "Independent concept", body: "Mira Atelier is a fictional artist-world created by VAELTX. No products are sold and no commissions are accepted." }], { label: "View the work", href: "/concepts/mira-atelier/work" }),
  route("work", "Work", "gallery", "A small collection of imagined places.", "Original illustration concepts made for this portfolio. Open a piece to inspect its composition and notes.", [{ heading: "Moon garden", body: "An imagined night garden in ink, muted mineral color and soft paper grain.", items: ["midnight-garden", "borrowed-light", "quiet-orchard"] }, { heading: "Artwork disclosure", body: "These original concept images are not commissioned client work and are not offered for sale." }], { label: "Read the commission process", href: "/concepts/mira-atelier/commissions" }),
  route("work/midnight-garden", "Midnight garden", "artwork", "Midnight garden.", "An original illustration study in moonlit foliage, deep blue ink and warm paper.", [{ heading: "Artwork notes", body: "Illustrative concept · digital ink and gouache study · fictional artwork details for this portfolio." }], { label: "Ask about a commission", href: "/concepts/mira-atelier/commission-request" }),
  route("work/borrowed-light", "Borrowed light", "artwork", "Borrowed light.", "A quiet interior study about afternoon light passing through leaves.", [{ heading: "Artwork notes", body: "Illustrative concept · layered color study · no physical edition or original is available." }], { label: "Ask about a commission", href: "/concepts/mira-atelier/commission-request" }),
  route("work/quiet-orchard", "Quiet orchard", "artwork", "Quiet orchard.", "An imagined orchard rendered with softened edges and a restrained palette.", [{ heading: "Artwork notes", body: "Illustrative concept · watercolor-style composition · no client commission is implied." }], { label: "Ask about a commission", href: "/concepts/mira-atelier/commission-request" }),
  route("commissions", "Commissions", "commissions", "A commission begins with the story, not the size.", "A clear sequence for discussing a personal illustration without inventing timelines, deposits or availability.", [{ heading: "01 Tell me the idea", body: "The request begins with what the artwork is for and the feeling it should hold." }, { heading: "02 Confirm fit and format", body: "Format, references and practical constraints shape whether the concept fits." }, { heading: "03 Agree on direction", body: "A real artist would confirm scope, revisions, timing and any deposit before work begins." }, { heading: "04 Create and deliver", body: "Final files, licensing and delivery terms depend on the actual engagement." }], { label: "Open the request form demo", href: "/concepts/mira-atelier/commission-request" }),
  route("commission-request", "Commission request", "commission-form", "Tell me what the piece is for.", "A local-only request-form demonstration. No submission is sent, stored or accepted as a real commission.", [{ heading: "Useful first details", body: "A story, intended format and timing context give a commission conversation a clear start." }], { label: "Read the commission process", href: "/concepts/mira-atelier/commissions" }),
  route("about", "About", "about", "Quiet work, clear decisions.", "An independent concept artist profile designed without a fictional biography or client history.", [{ heading: "A point of view", body: "Artwork can be personal without making the path to understand or ask about it difficult." }, { heading: "Concept disclosure", body: "The artist, studio and work shown here are fictional concepts by VAELTX." }], { label: "Explore the artwork", href: "/concepts/mira-atelier/work" }),
  route("shop", "Shop", "shop", "Existing work, editions and studies.", "A catalog pattern for existing artworks. This concept has no inventory, prices or checkout.", [{ heading: "Catalog state", body: "Product pages demonstrate image, format, availability and shipping information without claiming a purchasable item." }], { label: "View a product detail concept", href: "/concepts/mira-atelier/shop/paper-study-01" }),
  route("shop/paper-study-01", "Paper study 01", "product", "Paper study 01.", "A fictional product-detail pattern for a small print edition.", [{ heading: "Product details", body: "Edition, dimensions, price, paper stock and shipping are omitted because no real product or inventory exists." }], { label: "Browse the collection", href: "/concepts/mira-atelier/shop" }),
  route("contact", "Contact", "contact", "A note about the artwork.", "This fictional artist does not accept messages or commissions. Contact VAELTX about the concept project.", [{ heading: "Concept boundary", body: "Nothing submitted on this site reaches an artist or business. The commission form is only an interaction demo." }], { label: "Contact VAELTX", href: "/contact" }),
];

const axiom: ConceptRoute[] = [
  route("", "Home", "home", "Strategy for decisions that cannot be solved by more noise.", "A concept advisory site that structures ambiguous questions into decisions a team can examine, challenge and act on.", [{ heading: "Evidence → criteria → decision", body: "Axiom treats an agreed decision model as part of the work, not a by-product of more information." }, { heading: "Four decision pressures", body: "Focus, sequencing, operating model and market choice create different questions and outputs." }, { heading: "Illustrative only", body: "Axiom Strategy is a fictional concept. Scenarios and frameworks show information design, not client results." }], { label: "Explore services", href: "/concepts/axiom-strategy/services" }),
  route("services", "Services", "index", "Start with the decision that is difficult to make.", "Four advisory lenses for organizing a complex choice.", [{ heading: "Growth strategy", body: "Clarify which growth questions deserve attention and what evidence would change the decision." }, { heading: "Operating model", body: "Examine the roles, routines and information flow a chosen direction would require." }, { heading: "Market prioritization", body: "Compare market options through explicit criteria, constraints and trade-offs." }, { heading: "Decision architecture", body: "Build a structured way to move from evidence and options to a decision." }], { label: "Open the framework", href: "/concepts/axiom-strategy/case-studies" }),
  route("services/growth-strategy", "Growth strategy", "service", "Decide where focused growth effort belongs.", "An illustrative service page for framing growth choices without claiming commercial outcomes.", [{ heading: "The decision", body: "Which opportunity is worth examining first, given evidence, constraints and the organization’s capacity?" }, { heading: "Questions explored", body: "What is known, what remains uncertain, and what would alter the choice?" }, { heading: "Possible outputs", body: "A prioritized question set, explicit options and a decision record." }], { label: "Discuss a similar question", href: "/concepts/axiom-strategy/contact" }),
  route("services/operating-model", "Operating model", "service", "Make the work support the intended direction.", "A demonstration of how operating questions can be explained and scoped.", [{ heading: "The decision", body: "Which roles, routines and information paths need to change for a strategy to be executable?" }, { heading: "Evidence first", body: "Current constraints and responsibilities must be mapped before a target structure is proposed." }, { heading: "Possible outputs", body: "A responsibility map, meeting rhythm and transition considerations." }], { label: "Discuss the context", href: "/concepts/axiom-strategy/contact" }),
  route("services/market-prioritization", "Market prioritization", "service", "Compare options through explicit criteria.", "A hypothetical market-choice framework, not a market recommendation.", [{ heading: "The decision", body: "Which markets merit further attention given fit, access, risk and available evidence?" }, { heading: "Trade-offs stay visible", body: "Every option can be examined against agreed criteria instead of a single synthetic score." }, { heading: "Possible outputs", body: "A decision field and an evidence plan for unresolved assumptions." }], { label: "See an illustrative scenario", href: "/concepts/axiom-strategy/case-studies/market-prioritization" }),
  route("services/decision-architecture", "Decision architecture", "service", "Give a complex decision a structure people can inspect.", "A capability concept built around objective, constraints, evidence, options and trade-offs.", [{ heading: "The decision", body: "How can a team agree what the choice is and what information belongs in it?" }, { heading: "The method", body: "Separate the objective, constraints, evidence, options, trade-offs and decision." }, { heading: "The boundary", body: "A framework improves clarity; it does not guarantee a correct outcome." }], { label: "Explore the decision field", href: "/concepts/axiom-strategy/case-studies/decision-field" }),
  route("industries", "Industries", "index", "Context changes the questions worth asking.", "Illustrative industry lenses designed without fictional client logos or sector results.", [{ heading: "Professional services", body: "Offer clarity, delivery capacity and a useful first conversation." }, { heading: "Consumer products", body: "Portfolio focus, distribution choices and operating constraints." }, { heading: "Technology", body: "Positioning, adoption questions and capability sequencing." }], { label: "View an industry lens", href: "/concepts/axiom-strategy/industries/professional-services" }),
  route("industries/professional-services", "Professional services", "industry", "A service offer is only as clear as its decision path.", "A fictional industry lens for professional-services firms.", [{ heading: "Typical pressure", body: "Clients need to understand the expertise, the decision it supports and the shape of an engagement." }, { heading: "Questions to examine", body: "What is the actual choice? Who must agree? Which parts of the offer are repeatable?" }, { heading: "No sector results claimed", body: "This is a demonstration lens, not evidence of advisory work for a real firm." }], { label: "Explore the services", href: "/concepts/axiom-strategy/services" }),
  route("industries/consumer-products", "Consumer products", "industry", "Keep product choices connected to operating reality.", "A fictional industry lens for consumer-product decisions.", [{ heading: "Typical pressure", body: "A product portfolio may compete for attention, supply and distribution capacity." }, { heading: "Questions to examine", body: "What must be true for a choice to work, and which assumptions need evidence?" }, { heading: "No market figures", body: "No market-size or growth number is presented as real." }], { label: "View an illustrative scenario", href: "/concepts/axiom-strategy/case-studies/portfolio-prioritization" }),
  route("industries/technology", "Technology", "industry", "Sequence capability without confusing activity for progress.", "A fictional industry lens for technology teams.", [{ heading: "Typical pressure", body: "Teams can have more possible work than decision capacity." }, { heading: "Questions to examine", body: "Which user or operating need comes first, and what evidence could disconfirm the plan?" }, { heading: "No fabricated results", body: "This page shows a decision pattern, not a real company outcome." }], { label: "Read an insight", href: "/concepts/axiom-strategy/insights/evidence-before-opinion" }),
  route("case-studies", "Illustrative scenarios", "index", "Decision scenarios, clearly labelled as examples.", "No Axiom client engagements or client outcomes are represented here.", [{ heading: "Portfolio prioritization", body: "A hypothetical team compares options through agreed criteria and visible constraints." }, { heading: "Decision field", body: "A sample decision is decomposed into objective, evidence, options and trade-offs." }], { label: "Open a scenario", href: "/concepts/axiom-strategy/case-studies/portfolio-prioritization" }),
  route("case-studies/portfolio-prioritization", "Portfolio prioritization", "scenario", "Illustrative scenario: choosing what to examine first.", "A hypothetical portfolio decision. No company or commercial result is represented.", [{ heading: "Context", body: "A fictional team has several possible initiatives and limited decision capacity." }, { heading: "Decision model", body: "Agree the objective, constraints, evidence, options and trade-offs before ranking anything." }, { heading: "Limitations", body: "Without real data, this page cannot recommend an initiative or quantify an outcome." }], { label: "Discuss a similar question", href: "/concepts/axiom-strategy/contact" }),
  route("case-studies/market-prioritization", "Market prioritization", "scenario", "Illustrative scenario: comparing market options.", "A hypothetical comparison framework with no invented market data.", [{ heading: "Context", body: "A team is deciding which market opportunity deserves further investigation." }, { heading: "Framework", body: "Criteria are agreed first; unknown values remain unknown rather than being filled with invented numbers." }, { heading: "What would require real data", body: "Market size, reachability, competitive intensity and operating capacity need dated sources." }], { label: "Review the framework", href: "/concepts/axiom-strategy/services/market-prioritization" }),
  route("case-studies/decision-field", "Decision field", "scenario", "Illustrative framework: the decision field.", "An original diagram for examining a complex choice.", [{ heading: "Six stages", body: "Objective → Constraints → Evidence → Options → Trade-offs → Decision." }, { heading: "A model is not an answer", body: "The diagram clarifies what to examine. A real decision still needs accountable owners and evidence." }], { label: "Explore decision architecture", href: "/concepts/axiom-strategy/services/decision-architecture" }),
  route("insights", "Insights", "index", "Notes on making decisions clearer.", "Short editorial concepts with no invented publication history or dates.", [{ heading: "Evidence before opinion", body: "A useful decision separates what is observed from what is assumed.", items: ["evidence-before-opinion"] }, { heading: "The shape of a decision", body: "A choice becomes easier to challenge when criteria and constraints are visible.", items: ["decision-models"] }], { label: "Read an insight", href: "/concepts/axiom-strategy/insights/evidence-before-opinion" }),
  route("insights/evidence-before-opinion", "Evidence before opinion", "article", "Evidence before opinion.", "A short concept note on separating observation, assumption and interpretation.", [{ heading: "Start with the claim", body: "Name the question the team is trying to answer before collecting every available fact." }, { heading: "Mark what is known", body: "Observed evidence, assumptions and interpretations should not share an unlabeled column." }, { heading: "Decide what could change the view", body: "A decision process becomes more honest when disconfirming evidence is allowed to matter." }], { label: "Explore decision architecture", href: "/concepts/axiom-strategy/services/decision-architecture" }),
  route("insights/decision-models", "Decision models", "article", "A decision model should expose its trade-offs.", "A short concept note about objectives, constraints and choice criteria.", [{ heading: "Objective", body: "What must the decision accomplish?" }, { heading: "Constraints", body: "What limits are real, and which are assumptions?" }, { heading: "Trade-offs", body: "What is gained and what is given up under each option?" }], { label: "View the decision field", href: "/concepts/axiom-strategy/case-studies/decision-field" }),
  route("about", "About", "about", "A structured conversation for a complex question.", "A concept operating philosophy without fictional consultants, offices or past engagements.", [{ heading: "What the model controls", body: "Question framing, evidence labels, criteria and documentation can be made explicit." }, { heading: "What it cannot promise", body: "No framework guarantees a commercial outcome or removes uncertainty from a real market." }], { label: "Explore the framework", href: "/concepts/axiom-strategy/case-studies/decision-field" }),
  route("contact", "Contact", "contact", "Bring the decision, not a polished brief.", "This fictional advisory concept does not accept inquiries. Contact VAELTX about the demonstration.", [{ heading: "Illustrative project", body: "Axiom Strategy is an Independent Concept Project by VAELTX. No advisory service is represented as available." }], { label: "Contact VAELTX", href: "/contact" }),
];

const vault: ConceptRoute[] = [
  route("", "Home", "home", "Cards worth collecting, described with the detail collectors expect.", "An original trading-card commerce concept with fictional artwork, local demo interactions and no real inventory or payment.", [{ heading: "Start with a set or a card", body: "Search, filter and inspect an original fictional catalog with condition and stock states kept visible." }, { heading: "Condition is part of the decision", body: "The concept selector demonstrates how condition descriptions can stay next to price and availability." }, { heading: "Checkout is a demo", body: "Cart state remains in this browser. No payment is processed." }], { label: "Browse cards", href: "/concepts/vault-tcg/cards" }),
  route("collections", "Collections", "collections", "Browse fictional sets.", "Original card-art and set labels created for this commerce UX concept.", [{ heading: "Ember Archive", body: "An imagined set of firelit observatories and small mythic creatures.", items: ["ember-archive"] }, { heading: "Tidal Index", body: "A fictional collection about glass reefs, tide maps and deep-sea birds.", items: ["tidal-index"] }], { label: "Open Ember Archive", href: "/concepts/vault-tcg/collections/ember-archive" }),
  route("collections/ember-archive", "Ember Archive", "collection", "Ember Archive.", "A fictional set with original card art and no purchasable inventory.", [{ heading: "Set details", body: "Collection number, rarity distribution and release history are intentionally omitted because this set is invented." }], { label: "Browse the catalog", href: "/concepts/vault-tcg/cards" }),
  route("collections/tidal-index", "Tidal Index", "collection", "Tidal Index.", "A fictional set with original card art and no purchasable inventory.", [{ heading: "Set details", body: "Collection number, rarity distribution and release history are intentionally omitted because this set is invented." }], { label: "Browse the catalog", href: "/concepts/vault-tcg/cards" }),
  route("collections/verdant-atlas", "Verdant Atlas", "collection", "Verdant Atlas.", "A fictional set with original card art and no purchasable inventory.", [{ heading: "Set details", body: "Collection number, rarity distribution and release history are intentionally omitted because this set is invented." }], { label: "Browse the catalog", href: "/concepts/vault-tcg/cards" }),
  route("search", "Search", "search", "Find a card, set or number.", "Search the fictional demo catalog. Results are local and no real stock is represented.", [{ heading: "Try a term", body: "Search names and set labels such as Ember, Archive or Tidal." }], { label: "Browse all cards", href: "/concepts/vault-tcg/cards" }),
  route("cards", "Cards", "catalog", "A catalog built for comparison.", "Every card and price on this page is fictional concept data. Nothing is for sale.", [{ heading: "Filter by what matters", body: "Game, set and condition patterns are demonstrated with original sample data." }], { label: "Open a card", href: "/concepts/vault-tcg/cards/ember-keeper" }),
  route("cards/ember-keeper", "Ember Keeper", "product", "Ember Keeper · 014 / Ember Archive.", "An original fictional card concept for demonstrating product details, condition selection and a local cart.", [{ heading: "Card details", body: "Fictional artwork · set number 014 · concept condition states · no real price or inventory." }], { label: "Explore the set", href: "/concepts/vault-tcg/collections/ember-archive" }),
  route("cards/tideglass-heron", "Tideglass Heron", "product", "Tideglass Heron · 008 / Tidal Index.", "An original fictional card concept for demonstrating product media and condition states.", [{ heading: "Card details", body: "Fictional artwork · set number 008 · no real price or inventory." }], { label: "Explore collections", href: "/concepts/vault-tcg/collections" }),
  route("cards/moss-oracle", "Moss Oracle", "product", "Moss Oracle · 021 / Verdant Atlas.", "An original fictional card concept for demonstrating product details, condition selection and a local cart.", [{ heading: "Card details", body: "Fictional artwork · set number 021 · concept condition states · no real price or inventory." }], { label: "Explore Verdant Atlas", href: "/concepts/vault-tcg/collections/verdant-atlas" }),
  route("cards/star-forager", "Star Forager", "product", "Star Forager · 031 / Ember Archive.", "An original fictional card concept for demonstrating product details, condition selection and a local cart.", [{ heading: "Card details", body: "Fictional artwork · set number 031 · concept condition states · no real price or inventory." }], { label: "Explore Ember Archive", href: "/concepts/vault-tcg/collections/ember-archive" }),
  route("cart", "Cart", "cart", "Review the cards in your demo cart.", "This local cart demonstrates quantity and removal behavior. Nothing is reserved or purchased.", [{ heading: "Demo state", body: "Cart contents are stored in this browser only and disappear if browser storage is cleared." }], { label: "Continue browsing", href: "/concepts/vault-tcg/cards" }),
  route("account", "Account", "account", "A simple collector account concept.", "No account or authentication is connected.", [{ heading: "Account state", body: "Orders and saved cards are demonstrated as local interface patterns only." }], { label: "View demo orders", href: "/concepts/vault-tcg/account/orders" }),
  route("account/orders", "Orders", "orders", "No orders yet.", "Your future order history would appear here in a real store. This concept has no payment system.", [{ heading: "Empty state", body: "The pattern explains what belongs here without presenting sample purchases as real." }], { label: "Continue browsing", href: "/concepts/vault-tcg/cards" }),
  route("account/wishlist", "Wishlist", "wishlist", "A list for cards to revisit.", "Saved items use local browser state. They are not associated with a real account.", [{ heading: "Saved cards", body: "Use the save control on a demo product to add it to this browser’s concept wishlist." }], { label: "Browse cards", href: "/concepts/vault-tcg/cards" }),
  route("shipping", "Shipping", "shipping", "Shipping facts belong next to the purchase decision.", "A shipping-information pattern without invented rates, carriers or delivery promises.", [{ heading: "What a real store should disclose", body: "Shipping regions, rates, packaging, insurance and timing must be defined before this page is used commercially." }, { heading: "Concept state", body: "No order is accepted and no delivery estimate is available." }], { label: "Browse cards", href: "/concepts/vault-tcg/cards" }),
  route("faq", "FAQ", "faq", "Questions about the card-store concept.", "Clear answers for a fictional catalog and a non-payment checkout flow.", [{ heading: "Are these real trading cards?", body: "No. The cards and artwork are original fictional concepts." }, { heading: "Can I buy a card?", body: "No. Cart and checkout interactions are local demonstrations only." }, { heading: "Are prices or stock real?", body: "No. The concept does not publish commercial prices or inventory." }, { heading: "Does checkout process payment?", body: "No payment provider is connected or invoked." }], { label: "Open checkout demo", href: "/concepts/vault-tcg/checkout-demo" }),
  route("contact", "Contact", "contact", "Need help with a real order?", "This fictional store has no support team. Contact VAELTX about the Vault TCG concept.", [{ heading: "Concept boundary", body: "No message here reaches a shop or merchant." }], { label: "Contact VAELTX", href: "/contact" }),
  route("checkout-demo", "Checkout demo", "checkout", "A checkout flow that never charges.", "Concept checkout — payment is not processed. Do not enter real personal or payment details.", [{ heading: "Demo steps", body: "Contact → shipping → delivery → payment placeholder → review. No details are submitted or stored." }], { label: "Return to cart", href: "/concepts/vault-tcg/cart" }),
];

export const conceptRoutes: Record<string, ConceptRoute[]> = {
  "northstar-roofing": northstar,
  "mira-atelier": mira,
  "axiom-strategy": axiom,
  "vault-tcg": vault,
};

export const conceptNames: Record<string, string> = {
  "northstar-roofing": "Northstar Roofing", "mira-atelier": "Mira Atelier", "axiom-strategy": "Axiom Strategy", "vault-tcg": "Vault TCG",
};

export const conceptBase: Record<string, string> = Object.fromEntries(projects.map(p => [p.slug, p.route]));

export const pathOf = (base: string, path: string) => path ? `${base}/${path}` : base;
