import { money } from "./model";

export const escapeHTML = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
type Payload = Record<string, unknown>;
const titles: Record<string,string> = {
  verification: "CONFIRM YOUR EMAIL ADDRESS", signin: "YOUR SECURE SIGN-IN LINK",
  bid_confirmation: "BID CONFIRMED", outbid: "YOU'VE BEEN OUTBID", reserve_met: "RESERVE MET",
  auction_closed: "AUCTION CLOSED", closed_no_sale: "AUCTION CLOSED · NO SALE", winner: "YOU WON THE VAELTX WEBSITE AUCTION",
  backup_offer: "YOUR BACKUP OFFER", payment_reminder: "YOUR PAYMENT DEADLINE", payment_received: "PAYMENT CONFIRMED",
  onboarding: "PROJECT BRIEF RECEIVED", onboarding_available: "START YOUR WEBSITE", payment_expired: "PAYMENT DEADLINE PASSED",
  bid_accepted: "NEW VALID BID", late_payment_review: "PAYMENT NEEDS REVIEW",
};
export function renderAuctionEmail(input: {kind:string; owner:boolean; qa:boolean; payload:Payload; url:string; ownerDetails?:Payload; now?:number}) {
  const {kind,owner,qa,payload:p,url}=input;
  if (!/^https:\/\//.test(url)) throw new Error("Email CTA requires HTTPS.");
  const title = owner && kind==="winner" ? "WINNER DETERMINED" : titles[kind] || "AUCTION UPDATE";
  const rows: [string,string][]=[];
  const amount=(key:string,label:string)=>{if(typeof p[key]==="number") rows.push([label,`${money(p[key] as number)} USD`]);};
  if(kind==="outbid") { amount("previousAmount","YOUR PREVIOUS BID"); amount("currentHighest","CURRENT HIGHEST BID"); amount("nextMinimum","NEXT MINIMUM BID"); }
  else amount("amount",kind==="bid_confirmation"?"YOUR ACCEPTED BID":["winner","backup_offer","payment_reminder","payment_received"].includes(kind)?"WINNING AMOUNT":"AMOUNT");
  if(kind==="bid_confirmation") {amount("reserveAmount","PUBLIC RESERVE"); rows.push(["STATUS AT ACCEPTANCE",p.reserveMet?"CURRENTLY LEADING · RESERVE MET":"CURRENTLY LEADING · RESERVE NOT MET"]);}
  if(p.deadline) rows.push(["PAYMENT DEADLINE",new Date(String(p.deadline)).toUTCString()]);
  if(p.endsAt) {const seconds=Math.max(0,Math.floor((Date.parse(String(p.endsAt))-(input.now??Date.now()))/1000)); rows.push(["TIME REMAINING AT EMAIL PREPARATION",seconds?`${Math.floor(seconds/86400)} days · ${Math.floor(seconds%86400/3600)} hours · ${Math.floor(seconds%3600/60)} minutes`:"Deadline reached · check the authoritative auction state"]);}
  if(kind==="payment_received") rows.push(["PROJECT STATUS","READY TO BEGIN"]);
  if(owner) {amount("currentHighest","CURRENT HIGHEST");amount("nextMinimum","NEXT MINIMUM"); if(p.reserveMet!==undefined)rows.push(["RESERVE",p.reserveMet?"MET":"NOT MET"]); for(const [key,label] of [["fullName","BIDDER"],["businessName","BUSINESS"],["email","EMAIL"],["phone","PHONE"],["country","COUNTRY"]]) {const v=p[key]??input.ownerDetails?.[key];if(v)rows.push([label,String(v)]);} for(const [key,label] of [["bidId","BID REFERENCE"],["validBids","VALID BIDS"],["verifiedBidders","BIDDING PARTICIPANTS"],["at","ACCEPTED AT"]])if(p[key]!==undefined)rows.push([label,String(p[key])]); }
  const cta=owner?"OPEN PRIVATE DASHBOARD":kind==="verification"?"VERIFY EMAIL":kind==="signin"?"SIGN IN SECURELY":kind==="outbid"?"RETURN TO AUCTION":["winner","backup_offer","payment_reminder"].includes(kind)?"COMPLETE PAYMENT":["payment_received","onboarding_available"].includes(kind)?"START ONBOARDING":"VIEW YOUR AUCTION";
  const copy=qa?"This is an isolated QA fixture. Stripe TEST only; no real payment or live auction obligation.":["verification","signin"].includes(kind)?"Use this single-use link to verify your email and continue to your auction account. If you did not request it, you can ignore this email.":kind==="outbid"?"Another valid bid has taken the lead. Your account always shows the authoritative current state.":kind==="winner"?"Complete payment by the deadline above according to the published Auction Terms. No automatic card charge.":kind==="payment_received"?"Your payment has been verified. Continue with your website project brief.":"Review your auction account for the current state and agreed service scope.";
  const text=["VAELTX · Web & Conversion Studio",qa?"QA — STRIPE TEST":"TRANSACTIONAL AUCTION UPDATE",title,copy,...rows.map(([l,v])=>`${l}: ${v}`),cta,url,"Bidding is free. No automatic charges. Keep VAELTX emails easy to find; marking an expected message as Not spam can help your provider recognize future messages."].join("\n\n");
  const html=`<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"></head><body style="margin:0;background:#f5f4f0;color:#242321;font-family:Arial,Helvetica,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:#fff;border:1px solid #dedbd4;border-radius:12px"><tr><td style="padding:28px 24px;border-bottom:1px solid #eee"><strong style="font-size:24px;letter-spacing:2px">VAELTX<span style="color:#b84918">.</span></strong><div style="font-size:12px;color:#68645d;margin-top:6px">Web &amp; Conversion Studio</div></td></tr><tr><td style="padding:28px 24px"><span style="font-size:11px;letter-spacing:1px;color:#874019;background:#fff2e8;padding:6px 9px">${qa?"QA — STRIPE TEST":owner?"PRIVATE OWNER OPERATIONS":"AUCTION UPDATE"}</span><h1 style="font-size:25px;line-height:1.25;margin:22px 0 14px">${escapeHTML(title)}</h1><p style="font-size:15px;line-height:1.7;color:#625e57">${escapeHTML(copy)}</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e8e4dd;background:#faf9f6">${rows.map(([l,v])=>`<tr><td style="padding:14px 16px;border-bottom:1px solid #eee"><div style="font-size:10px;letter-spacing:1px;color:#6b665d">${escapeHTML(l)}</div><div style="font-size:18px;line-height:1.5;font-weight:bold;word-break:break-word">${escapeHTML(v)}</div></td></tr>`).join("")}</table><table role="presentation" cellpadding="0" cellspacing="0" style="margin:24px 0"><tr><td bgcolor="#242321" style="border-radius:5px"><a href="${escapeHTML(url)}" style="display:inline-block;padding:15px 20px;color:#fff;font-size:12px;font-weight:bold;text-decoration:none">${cta} &rarr;</a></td></tr></table><p style="font-size:12px;line-height:1.6;word-break:break-all">Button not opening? <a href="${escapeHTML(url)}" style="color:#874019">${escapeHTML(url)}</a></p></td></tr><tr><td style="padding:20px 24px;border-top:1px solid #eee;font-size:12px;line-height:1.7;color:#6b665d">VAELTX &middot; Transactional auction message.<br>Bidding is free. No automatic charges.<br>Mark an expected message as Not spam to help your provider recognize future VAELTX emails. Delivery to Inbox or Primary is not guaranteed.</td></tr></table></td></tr></table></body></html>`;
  return {html,text};
}
