import Image from "next/image";
import Link from "next/link";
import { ContentSection, Eyebrow, SiteShell } from "@/components/SiteShell";

const preview = "https://asterandform.vercel.app/preview";

function Capture({ name, alt, mobile = false }: { name: string; alt: string; mobile?: boolean }) {
  return <Image src={`/images/aster-${name}.webp`} width={mobile ? 375 : 1425} height={mobile ? 812 : 891} alt={alt} sizes={mobile ? "(max-width: 767px) 70vw, 300px" : "(max-width: 767px) 100vw, 1100px"} loading="lazy" />;
}

export function AsterCaseStudy() {
  return <SiteShell mode="canvas" className="case-study case-aster-form"><main id="main" tabIndex={-1}>
    <section className="case-hero aster-case-hero">
      <div className="case-hero-top"><Eyebrow>FEATURED CONCEPT / ASTER &amp; FORM</Eyebrow><span>VAELTX / EDITORIAL + EXPERIENCE DESIGN</span></div>
      <div className="case-hero-title"><h1>A considered experience, from first impression to next step.</h1><p>A fictional interior consultation atelier. Premium web design, a coherent service journey and an interactive reservation preview carry the same visual identity through every step.</p><div className="aster-hero-actions"><a className="button button-primary" href={preview}>Explore the safe demo <span aria-hidden="true">↗</span></a><Link className="aster-hero-contact" href="/contact">Discuss a similar project <span aria-hidden="true">→</span></Link></div></div>
      <div className="case-meta"><div><span>FOCUS</span><b>Editorial identity · premium web design · responsive UX</b></div><div><span>DEMO</span><b>Synthetic reservations · client portal · studio console</b></div><div><span>STATUS</span><b>Full-stack certification pending · technical work paused</b></div></div>
      <figure className="aster-hero-capture"><Image src="/images/aster-marketing-desktop.webp" width={1440} height={900} alt="Authentic ASTER & FORM public homepage with editorial typography and atmospheric concept interior imagery" sizes="(max-width: 767px) 100vw, 650px" priority /><figcaption>01 / PUBLIC WEBSITE · AUTHENTIC DESKTOP CAPTURE</figcaption></figure>
      <p className="case-disclosure"><strong>Independent Concept Project — Designed and Developed by VAELTX.</strong> Fictional studio and demonstration appointments. No real clients or payments. Production authentication has not been validated for this case study.</p>
    </section>

    <ContentSection number="01" label="DESIGN / SERVICE EXPERIENCE" title="Atmosphere with a clear next step."><div className="aster-copy-grid"><div><span className="case-subhead">THE CONCEPT BRIEF</span><p>Explore a premium studio website that helps visitors understand a visual point of view, compare three consultations and follow a reservation interface without losing the sense of calm.</p><p>The business, services, fees and interior imagery are conceptual. This is not a commissioned interior project or a real booking service.</p></div><div><span className="case-subhead">THE DESIGN RESPONSE</span><p>Warm neutral tones, expressive serif typography and restrained navigation establish the identity. Clear service names, durations and next actions bring structure to an otherwise atmospheric experience.</p><p>VAELTX designed and developed the concept website and its responsive interfaces. The presentation demonstrates design and public preview behavior; full-stack certification remains pending.</p></div></div></ContentSection>

    <section className="aster-experience-stage"><div className="section-shell"><div className="section-kicker"><Eyebrow number="02">THE SAFE INTERACTIVE WALKTHROUGH</Eyebrow><span>PREVIEW / SYNTHETIC UI / NO PERSISTENCE</span></div><h2>A reservation journey you can inspect.</h2><p className="aster-stage-intro">Choose a fictional consultation and a sample time, then see a simulated confirmation. The preview explicitly states that it creates no appointment, sends no confirmation email and stores no client record.</p><figure className="aster-wide-capture"><Capture name="reservation-desktop" alt="ASTER synthetic reservation walkthrough with service selection, sample time slots and a simulate confirmation button" /><figcaption>RESERVATION INTERFACE / SAFE PUBLIC PREVIEW · NOT A LIVE RESERVATION</figcaption></figure><div className="aster-feature-grid">{[
      ["01 / COMPARE", "Understand the service.", "Three distinct consultation concepts show duration, description and an illustrative fee before the next step."],
      ["02 / CHOOSE", "See the sequence.", "Service selection and sample time controls demonstrate the booking interface without calling a live reservation workflow."],
      ["03 / CONFIRM", "Make the outcome explicit.", "The simulated confirmation repeats the selected service and time, with a clear statement that no appointment was created."],
    ].map(([label, title, description]) => <article key={label}><span>{label}</span><h3>{title}</h3><p>{description}</p></article>)}</div><a className="text-link" href={preview}>Explore the reservation preview <span aria-hidden="true">↗</span></a></div></section>

    <ContentSection number="03" label="PORTAL / STUDIO CONCEPTS" title="The experience beyond the public website."><p className="aster-portal-intro">Two synthetic views illustrate how the same identity could carry into client and studio workflows. These are public, read-only concept screens; their example records and counts do not represent actual users or operational activity.</p><div className="aster-portal-grid"><figure><Capture name="client-desktop" alt="Synthetic ASTER client portal example, labelled as fictional records without Supabase access" /><figcaption>CLIENT PORTAL / SYNTHETIC REPRESENTATION</figcaption></figure><figure><Capture name="console-desktop" alt="Synthetic ASTER studio console example with read-only illustrative appointment counts and availability information" /><figcaption>STUDIO CONSOLE / DISPLAY ONLY · NO ADMIN PRIVILEGES</figcaption></figure></div></ContentSection>

    <section className="aster-responsive section-shell"><div><Eyebrow number="04">RESPONSIVE DESIGN</Eyebrow><h2>Editorial on desktop. Clear on mobile.</h2><p>The mobile layout gives the headline, service choices and actions room to breathe. Navigation and preview tabs adapt to a narrower reading order.</p><p>Both images are authentic captures at a 390 × 844 browser viewport. The interior imagery is concept imagery from the original application; it is not proof of commissioned interior work.</p></div><div className="aster-mobile-pair"><figure><Capture name="marketing-mobile" alt="Authentic mobile ASTER homepage showing the editorial identity and service introduction" mobile /><figcaption>PUBLIC WEBSITE / MOBILE</figcaption></figure><figure><Capture name="reservation-mobile" alt="Authentic mobile ASTER synthetic reservation interface with conceptual service selection" mobile /><figcaption>SAFE WALKTHROUGH / MOBILE</figcaption></figure></div></section>

    <ContentSection number="05" label="VERIFIED SCOPE / PENDING WORK" title="A precise boundary around the evidence."><div className="aster-copy-grid"><div><span className="case-subhead">PUBLIC EXPERIENCE VERIFIED</span><ul className="aster-verified-list"><li>Next.js / React interface, responsive CSS and Vercel hosting</li><li>Premium editorial website and visual identity</li><li>Service presentation and synthetic reservation controls</li><li>Public preview tabs for client and studio concepts</li></ul></div><div className="aster-boundary"><span className="case-subhead">FULL-STACK CERTIFICATION PENDING</span><p>This case does not certify production authentication, private reservation ownership, administrative permissions or backend behavior. The public preview does not validate those protected workflows.</p><p>Technical development remains paused. No live customer activity, paid engagement or certified production platform is claimed.</p></div></div></ContentSection>

    <section className="case-conclusion"><div className="section-shell"><Eyebrow number="06">DESIGN + DEVELOPMENT BY VAELTX</Eyebrow><h2>Explore the experience. Define your own scope.</h2><p>See the safe synthetic walkthrough or discuss a premium website and service experience with VAELTX. Deliverables, integrations and validation are agreed for each real project.</p><div className="case-conclusion-actions"><a className="button button-primary" href={preview}>Explore the safe demo <span aria-hidden="true">↗</span></a><Link className="button button-secondary" href="/contact">Start a project</Link></div><p className="aster-final-disclosure">Independent Concept Project — Designed and Developed by VAELTX. Full-stack certification pending.</p></div></section>
    <section className="next-project"><Link href="/work/northstar-roofing" className="next-project-link"><span><Eyebrow>NEXT PROJECT / LOCAL SERVICE</Eyebrow><strong>Northstar Roofing</strong><span className="next-project-title">Trust before the first conversation.</span><span className="next-arrow" aria-hidden="true">↗</span></span></Link></section>
  </main></SiteShell>;
}
