import Image from "next/image";
import Link from "next/link";
import { ContentSection, Eyebrow, SiteShell } from "@/components/SiteShell";
import { PortfolioPreviewImage } from "@/components/PortfolioPreviewImage";

const application = "https://vaeltx-orynt-ai-concept.vercel.app/";

function ProductCapture({ name, alt, mobile = false }: { name: string; alt: string; mobile?: boolean }) {
  return <Image src={`/images/orynt-${name}.webp`} width={mobile ? 375 : 1425} height={mobile ? 812 : 891} alt={alt} sizes={mobile ? "(max-width: 767px) 70vw, 300px" : "(max-width: 767px) 100vw, 1100px"} loading="lazy" />;
}

export function OryntCaseStudy() {
  return <SiteShell mode="canvas" className="case-study case-orynt-ai"><main id="main" tabIndex={-1}>
    <section className="case-hero orynt-case-hero">
      <div className="case-hero-top"><Eyebrow>FEATURED CONCEPT / ORYNT AI</Eyebrow><span>VAELTX / DESIGN + DEVELOPMENT</span></div>
      <div className="case-hero-title"><h1>A clearer picture of the work.</h1><p>An editorial product website and a working operations workspace. Designed to turn scattered updates into a view people can explore, question and understand.</p><div className="orynt-hero-actions"><a className="button button-primary" href={application}>Explore the application <span aria-hidden="true">↗</span></a><Link className="orynt-hero-contact" href="/contact">Discuss a similar project <span aria-hidden="true">→</span></Link></div></div>
      <div className="case-meta"><div><span>SECTOR</span><b>Functional SaaS concept · operations analytics</b></div><div><span>SCOPE</span><b>Product design · responsive UI · web development</b></div><div><span>DELIVERY</span><b>Public website + technically verified frontend demo</b></div></div>
      <figure className="orynt-hero-capture"><Image src="/images/orynt-marketing-desktop.webp" width={1440} height={900} alt="Authentic ORYNT product website with editorial typography and a sample project overview" sizes="(max-width: 767px) 100vw, 650px" priority /><figcaption>01 / PUBLIC PRODUCT WEBSITE · DESKTOP CAPTURE</figcaption></figure>
      <p className="case-disclosure"><strong>Independent Concept Project — Designed and Developed by VAELTX.</strong> Not commissioned client work. Fictional teams and synthetic data. No live commercial AI service.</p>
    </section>

    <ContentSection number="01" label="THE DESIGN PROBLEM" title="A useful number needs context."><div className="orynt-copy-grid"><div><span className="case-subhead">CONCEPT BRIEF</span><p>Explore how an operations lead could move from an overview to the projects behind it, understand why a signal appears and build a report without losing context.</p><p>This is a self-directed design problem, not a claim about a real customer or research engagement.</p></div><div><span className="case-subhead">THE RESPONSE</span><p>One connected visual system links a calm product website with a denser workspace. Consistent labels, visible reporting periods and inspectable tables keep the interface grounded in the same dataset.</p><p>VAELTX designed and developed the website, responsive workspace, reusable UI and deterministic reporting logic.</p></div></div></ContentSection>

    <section className="orynt-product-stage"><div className="section-shell"><div className="section-kicker"><Eyebrow number="02">THE PRODUCT IN USE</Eyebrow><span>AUTHENTIC PUBLIC APPLICATION CAPTURES</span></div><h2>From overview to understanding.</h2><p className="orynt-stage-intro">The website introduces the idea. The workspace lets visitors examine it: projects, delivery, milestones and attention signals share one fixed synthetic snapshot.</p><figure className="orynt-desktop-capture"><ProductCapture name="workspace-desktop" alt="ORYNT desktop workspace showing a 30-day overview, delivery chart and explainable project signals" /><figcaption>DESKTOP / 1440 × 900 · ACTUAL APPLICATION, SYNTHETIC OBSERVATIONS</figcaption></figure><div className="orynt-feature-grid">{[
      ["01 / DISCOVER", "Find the relevant work.", "Search 20 sample projects, filter by team, status and priority, sort the results and open project details."],
      ["02 / UNDERSTAND", "Inspect the signal.", "Attention rules expose overdue work, delivery gaps and capacity concerns. The reasoning is deterministic and visible; it is not a generative AI prediction."],
      ["03 / TAKE IT FURTHER", "Build a usable report.", "Switch between 7, 30 and 90 days, regroup by week or team, inspect the underlying rows and export them as CSV."],
    ].map(([label, title, description]) => <article key={label}><span>{label}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>

    <ContentSection number="03" label="INTERACTION / DATA" title="The numbers show their workings."><div className="orynt-report-copy"><p>Changing the reporting window recalculates the view. Weekly delivery uses differences between cumulative snapshots, so the chart describes work added during the period rather than repeating cumulative totals.</p><p>Report controls change the displayed table and chart together. In the captured 30-day example, the six team totals sum to the same 285 completed tasks.</p></div><figure className="orynt-report-capture"><ProductCapture name="reports-desktop" alt="ORYNT report builder grouped by team, showing the chart and exact data table for 285 synthetic completed tasks" /><figcaption>REPORT BUILDER / 30 DAYS · GROUPED BY TEAM · SYNTHETIC DATA</figcaption></figure></ContentSection>

    <section className="orynt-responsive section-shell"><div className="orynt-responsive-copy"><Eyebrow number="04">RESPONSIVE PRESENTATION</Eyebrow><h2>The same product. A considered mobile view.</h2><p>The marketing page preserves its editorial reading order. In the workspace, navigation moves into a drawer, summary cards stack and wide tables keep a contained scroll area.</p><p>These images were captured from the public application at a real 390 × 844 browser viewport. They are product screenshots, not redesigned mockups or editable design files.</p><a className="text-link" href={`${application}app`}>Try the workspace <span aria-hidden="true">↗</span></a></div><div className="orynt-mobile-pair"><figure><ProductCapture name="marketing-mobile" alt="Actual mobile ORYNT marketing page, with the product headline and demo action" mobile /><figcaption>PRODUCT WEBSITE / MOBILE</figcaption></figure><figure><ProductCapture name="workspace-mobile" alt="Actual mobile ORYNT workspace, with reporting controls and stacked summary cards" mobile /><figcaption>WORKSPACE / MOBILE</figcaption></figure></div></section>

    <ContentSection number="05" label="IMPLEMENTATION / BOUNDARIES" title="Real implementation. Explicit limits."><div className="orynt-technical-grid"><div><span className="case-subhead">VERIFIED TECHNOLOGIES</span><ul><li>Next.js App Router, React and TypeScript</li><li>Reusable UI components and responsive CSS</li><li>Deterministic analytics and CSV generation</li><li>Local browser preferences and saved report views</li><li>Vercel hosting</li></ul></div><div><span className="case-subhead">DATA / CONCEPT BOUNDARY</span><p>A bundled synthetic fixture keeps the demo available. An optional read-only Supabase snapshot can supply the same demo data, with validation and a bundled fallback.</p><p>No production customer records, account authentication, subscription billing or live commercial AI are represented. The concept demonstrates product design and working frontend behavior, not a certified production SaaS platform.</p></div></div></ContentSection>

    <section className="case-conclusion"><div className="section-shell"><Eyebrow number="06">DESIGN + DEVELOPMENT BY VAELTX</Eyebrow><h2>See the thinking. Use the interface.</h2><p>Explore the original public concept or talk to VAELTX about a website, product interface or responsive application with a clearly agreed scope.</p><div className="case-conclusion-actions"><a className="button button-primary" href={application}>Explore the application <span aria-hidden="true">↗</span></a><Link className="button button-secondary" href="/contact">Start a project</Link></div><p className="orynt-final-disclosure">Independent Concept Project — Designed and Developed by VAELTX.</p></div></section>
    <section className="next-project"><Link href="/work/aster-form" className="next-project-link"><span><Eyebrow>NEXT PROJECT / EDITORIAL &amp; BOOKING</Eyebrow><strong>ASTER &amp; FORM</strong><span className="next-project-title">A considered experience, from first impression to next step.</span><span className="next-arrow" aria-hidden="true">↗</span></span><PortfolioPreviewImage slug="aster-form" width={230} height={150} alt="" loading="lazy" /></Link></section>
  </main></SiteShell>;
}
