import Link from "next/link";
import Image from "next/image";
import { projects, conceptBase, conceptNames, conceptRoutes, pathOf, type ConceptRoute } from "@/lib/content";
import { ProjectNav } from "@/components/ProjectNav";
import { DemoForm } from "@/components/concepts/DemoForm";
import { AreaSearch, InspectionReport, QuoteStarter, ServiceFit, StickyQuoteBar } from "@/components/concepts/NorthstarInteractive";
import { DecisionField, MiraGallery, ProjectFAQ, VaultHeroCards } from "@/components/ProjectInteractions";
import { VaultExperience } from "@/components/VaultExperience";
import { vaultProducts } from "@/lib/vault";
import { Eyebrow } from "@/components/SiteShell";

export function ProjectShell({ concept, children, page = "" }: { concept: string; children: React.ReactNode; page?: string }) {
  const name = conceptNames[concept];
  return <div className={`project-site project-site-${concept}`} data-concept={concept} data-page={page}>
    <a className="project-skip-link" href="#project-main">Skip to concept content</a>
    <ProjectNav concept={concept}/>{children}
    <footer className="project-footer" data-project-footer><div className="project-footer-lead"><span>INDEPENDENT CONCEPT PROJECT / VAELTX</span><h2>{name}</h2><p>This is a self-directed interface concept, not a real business or client engagement.</p><Link href="/work">Return to the VAELTX portfolio <span aria-hidden="true">↗</span></Link></div><div className="project-footer-links"><Link href={conceptBase[concept]}>Concept home</Link><Link href={`${conceptBase[concept]}/contact`}>Contact boundary</Link><Link href="/work">VAELTX work</Link></div></footer>
  </div>;
}

function ProjectHome({ concept }: { concept: string }) {
  const base = conceptBase[concept];
  const visual = projects.find(project => project.slug === concept)?.visual ?? "";
  if (concept === "northstar-roofing") return <main tabIndex={-1} id="project-main" className="northstar-home">
    <section className="north-hero" data-north-hero><div className="north-hero-copy"><Eyebrow>RESIDENTIAL ROOFING / CONCEPT</Eyebrow><h1>Know what your roof needs before you commit to the next step.</h1><p>A clear inspection path for repair concerns, storm damage and planned replacement. This is an independent concept — no roofing service is offered.</p><div className="north-hero-actions"><Link className="north-button" href={`${base}/request-an-inspection`}>Request an inspection <span aria-hidden="true">↗</span></Link><Link className="north-text-link" href={`${base}/services`}>Explore services <span aria-hidden="true">→</span></Link></div><small>Sample concept · no appointment is booked</small></div><div className="north-hero-visual"><Image priority sizes="(max-width: 767px) 100vw, 50vw" width={799} height={449} src={visual} alt="AI-generated concept image of a warm white residence with a graphite standing seam roof; not a real customer property"/><div className="north-visual-label"><span>01 / INSPECTION PATH</span><b>Illustrative image · not a real property</b></div><QuoteStarter/></div></section>
    <section className="north-situation"><div className="north-section-head"><Eyebrow>01 / START WITH THE SITUATION</Eyebrow><h2>What are you noticing?</h2><p>A visitor does not need to diagnose the roof to find a useful next question.</p></div><ServiceFit/></section>
    <section className="north-report-section"><div className="north-section-head"><Eyebrow>02 / INSPECTION EVIDENCE</Eyebrow><h2>An inspection should leave a clear record.</h2></div><InspectionReport/></section>
    <section className="north-areas-section"><div className="north-section-head"><Eyebrow>03 / AREA PATTERN</Eyebrow><h2>Coverage should be easy to verify.</h2><p>These districts are fictional examples, not real service areas.</p></div><AreaSearch/></section>
    <section className="north-final-cta"><span>INDEPENDENT CONCEPT / NO REAL BOOKINGS</span><h2>Describe what you can safely see.</h2><Link className="north-button" href={`${base}/request-a-quote`}>Open the form demo <span aria-hidden="true">↗</span></Link></section><StickyQuoteBar/>
  </main>;

  if (concept === "mira-atelier") return <main tabIndex={-1} id="project-main" className="mira-home">
    <section className="mira-hero"><div className="mira-hero-copy"><Eyebrow>ORIGINAL WORK &amp; COMMISSIONS</Eyebrow><h1>Illustration for stories, spaces and people worth remembering.</h1><p>A small collection of original concept artwork, with a separate path for a personal commission.</p><div className="mira-hero-actions"><Link className="mira-button" href={`${base}/work`}>View the work <span aria-hidden="true">↗</span></Link><Link className="mira-link" href={`${base}/commissions`}>Commission an original <span aria-hidden="true">→</span></Link></div><span className="mira-concept-caption">Independent concept by VAELTX · artwork created for demonstration</span></div><Link className="mira-hero-art" href={`${base}/work/midnight-garden`}><Image unoptimized priority fetchPriority="high" width={960} height={1200} src="/images/mira-midnight-garden.webp" alt="Original illustration concept of a pale moon above an indigo garden with red flowers and fine ink branches"/><span>01 / MIDNIGHT GARDEN · OPEN STUDY ↗</span></Link></section>
    <section className="mira-journeys"><Link className="mira-journey mira-journey-commission" href={`${base}/commissions`}><span>01 / COMMISSION</span><strong>Made for one person, one story, one place.</strong><small>Learn the process <span aria-hidden="true">↗</span></small></Link><Link className="mira-journey mira-journey-shop" href={`${base}/shop`}><span>02 / EXISTING WORK</span><strong>Studies and pieces from the collection.</strong><small>Browse the concept catalog <span aria-hidden="true">↗</span></small></Link></section>
    <section className="mira-featured"><div className="mira-section-heading"><Eyebrow>SELECTED STUDIES / 03</Eyebrow><h2>A small collection of imagined places.</h2><Link className="mira-link" href={`${base}/work`}>View all work →</Link></div><MiraGallery base={base}/></section>
    <section className="mira-note"><span>THE ARTWORK IS THE COLOR.</span><p>Paper, ink and layered shapes lead the composition. Interface details stay quiet so the work remains easy to inspect.</p><Link href={`${base}/about`}>About this concept <span aria-hidden="true">↗</span></Link></section>
  </main>;

  if (concept === "axiom-strategy") return <main tabIndex={-1} id="project-main" className="axiom-home">
    <section className="axiom-hero"><div className="axiom-hero-copy"><Eyebrow>DECISION ARCHITECTURE / CONCEPT</Eyebrow><h1>Strategy for decisions that cannot be solved by more noise.</h1><p>Axiom structures ambiguous growth, operating and market questions into decisions teams can examine, challenge and act on.</p><div className="axiom-hero-actions"><Link className="axiom-button" href={`${base}/case-studies`}>Explore the scenarios <span aria-hidden="true">↗</span></Link><Link className="axiom-link" href={`${base}/services`}>See capabilities →</Link></div><small>Illustrative advisory concept · no client work or results represented</small></div><div className="axiom-hero-diagram"><span>DECISION FIELD / 06 STAGES</span><DecisionField base={base}/></div></section>
    <section className="axiom-thesis"><span>THE POINT OF VIEW / 01</span><h2>The cost of a strategy problem is often not lack of information. It is lack of an agreed decision model.</h2><div className="axiom-thesis-flow"><span>Evidence</span><b aria-hidden="true">→</b><span>Criteria</span><b aria-hidden="true">→</b><span>Decision</span></div></section>
    <section className="axiom-services"><div><Eyebrow>CAPABILITIES / 04</Eyebrow><h2>Different questions need different lenses.</h2></div><div>{conceptRoutes[concept].filter(item => item.path.startsWith("services/")).map((item, i) => <Link key={item.path} href={`${base}/${item.path}`}><span>0{i + 1}</span><strong>{item.label}</strong><small>{item.title}</small><b aria-hidden="true">↗</b></Link>)}</div></section>
    <section className="axiom-scenario-preview"><span>ILLUSTRATIVE ENGAGEMENT SCENARIO</span><h2>Frameworks can clarify a choice without pretending to choose for you.</h2><p>Explore a hypothetical portfolio decision with its inputs, trade-offs and limitations visible.</p><Link href={`${base}/case-studies/portfolio-prioritization`}>Open the scenario <span aria-hidden="true">↗</span></Link></section>
  </main>;

  return <main tabIndex={-1} id="project-main" className="vault-home"><section className="vault-hero"><div><Eyebrow>COLLECTOR DETAIL / COMMERCE CONCEPT</Eyebrow><h1>Cards worth collecting, described with the detail collectors expect.</h1><p>Search and inspect original fictional card concepts. No real inventory or payment is connected.</p><Link className="vault-hero-button" href={`${base}/cards`}>Browse cards <span aria-hidden="true">↗</span></Link><span className="vault-demo-note">ORIGINAL FICTIONAL CARD ART / DEMO VALUES ONLY</span></div><VaultHeroCards base={base}/></section><section className="vault-discovery"><div><Eyebrow>QUICK DISCOVERY</Eyebrow><h2>Start with a name, set or card number.</h2></div><div className="vault-category-links">{["Ember Archive", "Tidal Index", "Verdant Atlas", "All cards"].map((label, i) => <Link key={label} href={i === 3 ? `${base}/cards` : `${base}/collections/${label.toLowerCase().replaceAll(" ", "-")}`}><span>0{i + 1}</span>{label}<b aria-hidden="true">↗</b></Link>)}</div></section><section className="vault-home-products"><div className="vault-section-heading"><Eyebrow>CONCEPT CATALOG / 04 SAMPLE CARDS</Eyebrow><Link href={`${base}/cards`}>View all cards ↗</Link></div><VaultExperience kind="home" base={base}/></section><section className="vault-condition-note"><span>COLLECTOR DETAIL</span><h2>Condition is part of the decision.</h2><p>A real catalog needs a documented grading standard, product-specific photos and inventory behind every condition label.</p><Link href={`${base}/faq`}>Review concept details <span aria-hidden="true">↗</span></Link></section></main>;
}

function SectionContent({ concept, page, base }: { concept: string; page: ConceptRoute; base: string }) {
  return <div className={`project-content project-content-${concept} project-content-${page.kind}`}>
    {concept === "vault-tcg" && ["collections", "collection", "catalog", "product", "cart", "account", "orders", "wishlist", "checkout"].includes(page.kind) ? <div className="project-interaction"><VaultExperience kind={page.kind} base={base} collectionName={page.kind === "collection" ? page.label : undefined} product={page.kind === "product" ? vaultProducts.find(item => item.slug === page.path.split("/").at(-1)) : undefined}/></div> : null}
    {page.kind !== "faq" ? page.sections.map((section, index) => <section id={concept === "axiom-strategy" && page.kind === "article" ? `axiom-article-${index + 1}` : undefined} className="project-content-section" key={`${section.heading}-${index}`}><div className="project-content-label"><span>0{index + 1} / {page.label.toUpperCase()}</span><i/></div><div className="project-content-main"><h2>{section.heading}</h2><p>{section.body}</p>{section.items && <ul className="project-content-items">{section.items.map((item, i) => { const target = conceptRoutes[concept].find(route => route.path.endsWith(item) || route.path === item); return <li key={item}>{target ? <Link href={pathOf(base, target.path)}><span>0{i + 1}</span>{target.label}<b aria-hidden="true">↗</b></Link> : <span><b>0{i + 1}</b>{item}</span>}</li>; })}</ul>}</div></section>) : null}
    {concept === "northstar-roofing" && page.kind === "areas" ? <div className="project-interaction"><AreaSearch/></div> : null}
    {concept === "northstar-roofing" && ["service", "reviews", "warranty"].includes(page.kind) ? <div className="project-interaction"><InspectionReport/></div> : null}
    {concept === "northstar-roofing" && ["quote"].includes(page.kind) ? <div className="project-interaction" data-north-no-sticky><DemoForm kind="inspection" initialZip="" initialNeed="Not sure"/></div> : null}
    {concept === "northstar-roofing" && ["index"].includes(page.kind) ? <div className="project-interaction"><ServiceFit/></div> : null}
    {concept === "mira-atelier" && page.kind === "gallery" ? <MiraGallery base={base}/> : null}
    {concept === "mira-atelier" && page.kind === "artwork" ? <MiraGallery base={base} selected={page.path.split("/").at(-1)}/> : null}
    {concept === "mira-atelier" && page.kind === "commission-form" ? <div className="project-interaction"><DemoForm kind="commission"/></div> : null}
    {concept === "mira-atelier" && page.kind === "shop" ? <div className="mira-shop-preview"><article><Image unoptimized width={960} height={1200} src="/images/mira-borrowed-light.webp" alt="Original concept artwork: afternoon light through leaves"/><span>STUDY / 01</span><h3>Paper study 01</h3><p>Concept product · no stock or price</p><Link href={`${base}/shop/paper-study-01`}>Preview product detail →</Link></article></div> : null}
    {concept === "mira-atelier" && page.kind === "product" ? <div className="mira-product-concept"><Image unoptimized width={960} height={1200} src="/images/mira-borrowed-light.webp" alt="Original artwork concept showing warm light through a quiet studio window"/><div><span>PRODUCT DETAIL / CONCEPT</span><h3>Paper study 01</h3><p>Dimensions, paper, edition, price and shipping must be confirmed for a real product.</p><button type="button" disabled>Purchase unavailable in this concept</button></div></div> : null}
    {concept === "axiom-strategy" ? <div className="project-interaction"><DecisionField base={base}/></div> : null}
    {page.kind === "faq" ? <div className="project-interaction"><ProjectFAQ concept={concept}/></div> : null}
    {page.cta ? <div className={`project-page-cta project-page-cta-${concept}`}><span>{concept === "axiom-strategy" ? "ILLUSTRATIVE CONCEPT" : "INDEPENDENT CONCEPT / VAELTX"}</span><h2>{concept === "northstar-roofing" ? "Keep the next step clear." : concept === "mira-atelier" ? "A different story begins with a useful question." : concept === "axiom-strategy" ? "A framework can start a conversation." : "Continue exploring the demo catalog."}</h2><Link href={page.cta.href}>{page.cta.label} <span aria-hidden="true">↗</span></Link></div> : null}
  </div>;
}

export function ProjectPage({ concept, page, searchParams }: { concept: string; page: ConceptRoute; searchParams?: Record<string, string | string[] | undefined> }) {
  const base = conceptBase[concept];
  const title = page.path === "" ? conceptNames[concept] : page.label;
  if (page.kind === "home") return <ProjectShell concept={concept} page="home"><ProjectHome concept={concept}/></ProjectShell>;
  return <ProjectShell concept={concept} page={page.path}><main tabIndex={-1} id="project-main" className={`project-inner project-inner-${concept} project-inner-${page.kind}`}>
    <header className={`project-page-hero project-page-hero-${concept}`}><div className="project-page-breadcrumb"><Link href={base}>{conceptNames[concept]}</Link><span aria-hidden="true">/</span><span>{title}</span></div><Eyebrow>{page.kind === "scenario" ? "ILLUSTRATIVE ENGAGEMENT SCENARIO" : page.kind === "article" ? "AXIOM / INSIGHT" : `${conceptNames[concept].toUpperCase()} / INDEPENDENT CONCEPT`}</Eyebrow><h1>{page.title}</h1><p>{page.description}</p><span className="project-page-index">{page.path ? page.path.split("/").map((part, i) => <span key={`${part}-${i}`}>{part.toUpperCase()}{i < page.path.split("/").length - 1 ? " / " : ""}</span>) : "HOME"}</span></header>
    {concept === "mira-atelier" && page.kind === "commissions" ? <section className="mira-commission-steps">{page.sections.map((section, i) => <article key={section.heading}><span>0{i + 1}</span><h2>{section.heading}</h2><p>{section.body}</p></article>)}</section> : null}
    {concept === "axiom-strategy" && page.kind === "article" ? <aside className="axiom-article-toc"><span>ON THIS PAGE</span>{page.sections.map((section, i) => <a key={section.heading} href={`#axiom-article-${i + 1}`}>{section.heading}</a>)}</aside> : null}
    <SectionContent concept={concept} page={page} base={base}/>
    {concept === "vault-tcg" && page.kind === "search" ? <div className="project-interaction"><VaultExperience kind="search" base={base} query={Array.isArray(searchParams?.q) ? searchParams?.q[0] ?? "" : searchParams?.q ?? ""}/></div> : null}
    {concept === "northstar-roofing" && page.kind !== "quote" ? <StickyQuoteBar/> : null}
  </main></ProjectShell>;
}
