import Link from "next/link";
export default function GrantPrivacy() {
  return <main id="main" className="wg-main wg-narrow"><p className="wg-kicker">WEBSITE LAUNCH GRANT / PRIVACY</p><h1>Your application stays private.</h1><div className="wg-rules">
    <section><h2>Information you provide</h2><p>VAELTX requests your name, business name, verified email, country, city, business description and website goals. Website and social links are optional. Your agreements and the applicable rules version are recorded separately from your application.</p></section>
    <section><h2>What it is used for</h2><p>Account verification, eligibility checks, entry administration, selection communications and delivery of any service you purchase. Campaign contact consent does not subscribe you to unrelated marketing.</p></section>
    <section><h2>Service providers</h2><p>Supabase handles accounts and campaign records. Transactional email uses Supabase’s configured email delivery and Resend. Vercel hosts the website. Stripe processes available standalone service payments; card details are entered on Stripe’s hosted checkout.</p></section>
    <section><h2>Private entries and public totals</h2><p>Entry numbers are not passwords. Sign-in and ownership are required to view entry details. The public count contains no names, emails, applications or payment identifiers. Winner contact details and applications are not published without an appropriate basis and permission.</p></section>
    <section><h2>Abuse prevention</h2><p>Email verification, account-based limits and security checks prevent duplicate free entries. Temporary rate-limit keys use a keyed hash of account, email or network information. Those keys expire and are deleted within 24 hours on the next limiter request. A keyed hash is a privacy measure and does not make data anonymous.</p></section>
    <section><h2>Cookies and analytics</h2><p>Necessary sign-in cookies keep your account secure. The existing optional Meta marketing consent remains separate. Your application answers, name, email and payment data are not supplied to Meta by this campaign.</p></section>
    <section><h2>Retention and requests</h2><p>The campaign’s complete retention schedule, legal organizer information and applicable rights must be finalized in the Official Rules before participation opens. Contact <a href="mailto:vaeltxn@gmail.com">vaeltxn@gmail.com</a> with privacy, correction or deletion requests. Necessary entry and payment records may need to be retained for applicable obligations.</p></section>
  </div><Link href="/website-grant/official-rules" className="wg-button">Read the Official Rules ↗</Link></main>;
}
