import Link from "next/link";
import { campaignSnapshot } from "@/lib/website-grant-server";
import { campaignAvailability } from "@/lib/website-grant";
import { GrantCountdown, GrantPurchases } from "@/components/website-grant/GrantControls";

export const dynamic = "force-dynamic";
export default async function GrantPage() {
  const { campaign, validEntries, serverNow } = await campaignSnapshot(), availability = campaignAvailability(campaign, serverNow);
  const days = campaign?.start_at && campaign.end_at ? Math.ceil((Date.parse(campaign.end_at) - Date.parse(campaign.start_at)) / 86400000) : null;
  return <main id="main" className="wg-main"><section className="wg-hero"><div className="wg-hero-copy"><p className="wg-kicker">VAELTX / WEBSITE LAUNCH GRANT</p><h1>Your business.<br/>A new beginning.</h1><p className="wg-lead">A custom website for the business you’re building.</p><p>Website design + development.<br/>Domain included. First month of hosting included.</p><div className="wg-hero-actions"><Link className="wg-button" href="/website-grant/apply">{availability === "closed" ? "View campaign status" : "Get your free entry"} <span aria-hidden="true">↗</span></Link><Link className="wg-inline-link" href="#the-prize">Explore the prize ↓</Link></div><p className="wg-fine">No purchase necessary for the free entry. One per verified account.<br/>18+ · Eligibility restrictions apply.</p></div>
    <div className="wg-hero-card"><div className="wg-card-top"><span>ONE BUSINESS WILL BE SELECTED</span><span aria-hidden="true">↗</span></div><div className="wg-website-art" aria-hidden="true"><div className="wg-art-bar"><b>YOUR BUSINESS</b><span>● ● ●</span></div><div className="wg-art-body"><div className="wg-art-label">A CLEARER NEXT CHAPTER</div><div className="wg-art-title">Built around<br/>your ambition.</div><div className="wg-art-line"/><div className="wg-art-line short"/><div className="wg-art-cta">LET’S BEGIN ↗</div><div className="wg-art-orbit"/></div><div className="wg-art-bottom"><span>STRATEGY</span><span>DESIGN</span><span>DEVELOPMENT</span></div></div><div className="wg-card-caption"><h2>A custom VAELTX website</h2><span>$0 for the included prize scope</span></div><GrantCountdown end={campaign?.end_at || null} serverNow={serverNow} open={availability === "open"}/>{availability === "closed" && <p className="wg-notice">Applications are now closed. The selected business will be contacted using its application details.</p>}</div></section>
    {availability !== "open" && <div className="wg-status-banner" role="status"><span className="wg-status-dot" aria-hidden="true"/><p>{availability === "closed" ? "This campaign has closed." : "The campaign is being prepared. Applications and payments are not open yet."}</p><Link href="/website-grant/official-rules">Read campaign details ↗</Link></div>}
    <section className="wg-stats" aria-label="Campaign statistics"><div><strong>{validEntries === null ? "—" : validEntries.toLocaleString("en-US")}</strong><span>VALID ENTRIES</span>{validEntries === null && <p>Count available when connected</p>}</div><div><strong>{days === null ? "—" : days}</strong><span>CAMPAIGN DAYS</span>{days === null && <p>Dates announced at opening</p>}</div><div><strong>{campaign?.prize_quantity ?? "01"}</strong><span>WEBSITE TO BE AWARDED</span></div></section>
    <section id="the-prize" className="wg-prize"><div><p className="wg-kicker">01 / THE PRIZE</p><h2>A proper website.<br/>Built for your business.</h2><p className="wg-lead">Selected business pays $0 for the included scope.</p><p>Up to 5 custom pages, or one equivalent high-detail landing website. Designed and developed for desktop and mobile.</p></div><ul>{["Custom design + development", "Responsive desktop + mobile", "Contact and lead functionality", "Basic SEO structure", "Domain registration for the first year", "First month of hosting", "Launch support"].map((item, i) => <li key={item}><span>0{i + 1}</span>{item}<b aria-hidden="true">↗</b></li>)}</ul><div className="wg-prize-note"><p><strong>Your domain.</strong> First-year registration up to USD 20. Premium and aftermarket domains are excluded.</p><p><strong>Your choice after launch.</strong> Continue hosting with VAELTX, migrate your website, or arrange another hosting solution after the included first month.</p></div></section>
    <section className="wg-how"><p className="wg-kicker">02 / HOW IT WORKS</p><h2>A clear path from entry to launch.</h2><div className="wg-steps">{[["01", "Verify your email", "Create or sign in to your account. Verification protects the one-free-entry rule."], ["02", "Tell us about your business", "Submit your application and claim your unique free entry."], ["03", "Follow the campaign", "View your entry details and any purchases securely in your account."], ["04", "One business is selected", "The sales team evaluates applications under the published criteria. There is no random draw. The selected business is contacted privately."]].map(([n, title, text]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <GrantPurchases/>
    <section className="wg-faq"><p className="wg-kicker">03 / BEFORE YOU ENTER</p><h2>Clear terms. No guesswork.</h2>{[["Can I claim another free entry?", "Each verified account has one free entry per campaign. A new browser, a cleared cookie or another sign-in does not reset that limit."], ["Can I keep buying entries?", "When legally and operationally available, the same verified account may make repeated purchases of packages from 5 to 100 entries. There is no cumulative account cap in the proposed package structure."], ["Does a purchase guarantee selection?", "No. The sales team reviews eligible applications under published criteria. Additional entry quantity does not automatically improve a review score. Standalone services do not issue entries or influence selection."], ["Are all countries eligible?", "No. Payment currency and campaign eligibility are separate. Only the jurisdictions listed in the published Official Rules may participate."], ["When does the campaign begin?", "The campaign will open after its dates, eligibility, Official Rules and operational setup are finalized. No countdown starts during preparation."]].map(([q, a]) => <details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</section>
  </main>;
}
